# Generated by Django 3.2 on 2021-04-08 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myuser', '0001_initial'),
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameClanUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clan_profile', serialize=False, to='myuser.user')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_users', to='game.gameclan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gameclanchat',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='game.gameclan'),
        ),
        migrations.AddField(
            model_name='gameclan',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_clan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameclan',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='gamechatmessage',
            name='clan_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs', to='game.gameclanchat'),
        ),
        migrations.AddField(
            model_name='gamechatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_msgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
