# Generated by Django 3.1.7 on 2021-03-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gameclaninfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameclanchat',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.gameclanuser'),
            preserve_default=False,
        ),
    ]
