# Generated by Django 3.1.7 on 2021-03-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameclanchat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameclanchat',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='game.gameclan'),
        ),
        migrations.AlterField(
            model_name='gameclanuser',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_user', to='game.gameclan'),
        ),
    ]
