# Generated by Django 3.1.7 on 2021-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210331_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameclanchat',
            name='clan',
        ),
        migrations.RemoveField(
            model_name='gameclanuser',
            name='clan',
        ),
        migrations.AddField(
            model_name='gameclan',
            name='chat',
            field=models.ManyToManyField(to='game.GameClanChat'),
        ),
        migrations.AddField(
            model_name='gameclan',
            name='users',
            field=models.ManyToManyField(to='game.GameClanUser'),
        ),
    ]
