# Generated by Django 3.1.7 on 2021-04-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210401_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameclan',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='gameclan',
            name='users',
        ),
        migrations.AddField(
            model_name='gameclanchat',
            name='clan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='game.gameclan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameclanuser',
            name='clan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clan_user', to='game.gameclan'),
            preserve_default=False,
        ),
    ]
