# Generated by Django 3.1.7 on 2021-04-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210401_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameclanchat',
            old_name='user',
            new_name='ser',
        ),
        migrations.AlterField(
            model_name='gameclanuser',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_users', to='game.gameclan'),
        ),
    ]
