# Generated by Django 3.1.7 on 2021-04-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210401_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameclan',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gameclaninfo'),
        ),
        migrations.AlterField(
            model_name='gameclan',
            name='settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gameclansettings'),
        ),
        migrations.AlterField(
            model_name='gameclanchat',
            name='ser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameclanuser'),
        ),
        migrations.AlterField(
            model_name='gameclaninfo',
            name='description',
            field=models.TextField(default='Clan description'),
        ),
        migrations.AlterField(
            model_name='gameclaninfo',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
