# Generated by Django 3.1.7 on 2021-04-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210401_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameclanchat',
            name='ser',
        ),
        migrations.AddField(
            model_name='gameclanchat',
            name='clan_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clan_user_msgs', to='game.gameclanuser'),
            preserve_default=False,
        ),
    ]
